Quick-sort added
TesseractCoding/NeoAlgo-Docs pull request #123
Opened 2021-04-09 13:47 UTC by shivammahajancse

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#49)

2021-04-09 13:50 UTC, shivammahajancse commented
Please review @HarshCasper @ankitaggarwal23 @gat786 sir

2021-04-10 05:25 UTC, HarshCasper requested changes
Please use this [standard template](https://raw.githubusercontent.com/TesseractCoding/NeoAlgo-Docs/main/ARTICLE-TEMPLATE.mdx) for the purpose of writing articles.

2021-04-10 05:25 UTC, HarshCasper commented on docs/sorting-algorithms/Quick-sort.mdx
> +This can be done in-place, requiring small additional amounts of memory to perform the sorting.
Reword this line. It is being caught in the plagiarism checks.

2021-04-10 05:25 UTC, HarshCasper commented on docs/sorting-algorithms/Quick-sort.mdx
> +This can be done in-place, requiring small additional amounts of memory to perform the sorting.
Wrap all of this in one line

2021-04-10 05:25 UTC, HarshCasper commented on docs/sorting-algorithms/Quick-sort.mdx
> +* We do step 3 until we left with single element.
This should be after explanation

2021-04-10 05:25 UTC, HarshCasper commented on docs/sorting-algorithms/Quick-sort.mdx
> +
Give a detailed explanation as well. Write a paragraph or two explaining the algorithm

2021-04-10 05:25 UTC, HarshCasper commented on docs/sorting-algorithms/Quick-sort.mdx
> +* We do step 3 until we left with single element.
Use proper sentence formations. Also run them against grammarly checks. Most of them are improperly formatted

2021-04-10 05:25 UTC, HarshCasper commented on docs/sorting-algorithms/Quick-sort.mdx
> +* first we have to pick a pivot element.
`First we have to pick a pivot element`

2021-04-10 05:25 UTC, HarshCasper commented on docs/sorting-algorithms/Quick-sort.mdx
> +* Then partition the array according to pivot element(smaller or equal elements than pivot must lies on left side and greater on right).
`Partition the array according to the pivot element, where the smaller or equal elements compare to the pivot must lie on the left side and greater on the right side`

2021-04-10 05:25 UTC, HarshCasper commented on docs/sorting-algorithms/Quick-sort.mdx
> +* Then apply same steps 1 & 2 on the left part of pivot and right part of pivot recursively.
`Apply the previous two steps on the left part of the pivot and the right part of the pivot respectively`

2021-04-10 05:25 UTC, HarshCasper commented on docs/sorting-algorithms/Quick-sort.mdx
> +<img src="../../static/img/quick-sort.png" width="500" height="350"/>
Remove these images. If you created them, upload on Imgur and cross-reference them here

2021-04-10 05:25 UTC, HarshCasper commented on docs/sorting-algorithms/Quick-sort.mdx
> +<img src="../../static/img/quick-sort2.png" width="500" height="350"/>
Remove these images. If you created them, upload on Imgur and cross-reference them here

2021-04-10 07:23 UTC, shivammahajancse commented
All requested changes done @HarshCasper sir

2021-04-11 12:28 UTC, HarshCasper commented
Can you please make the same changes I asked here: https://github.com/TesseractCoding/NeoAlgo-Docs/pull/134

Thanks a lot for your contributions!

2021-04-12 10:55 UTC, shivammahajancse commented
All changes done @HarshCasper sir

2021-04-13 11:50 UTC, HarshCasper requested changes

2021-04-13 11:50 UTC, HarshCasper commented on docs/sorting-algorithms/quick-sort.mdx
> +# Time & Space Complexity
Use Heading-2

2021-04-13 11:50 UTC, HarshCasper commented on docs/sorting-algorithms/quick-sort.mdx
> +on n elements. So time complexity becomes: O(nlogn). And in average case also time complexity:O(nlogn).
Wrap all of this in one line. Also if you have already shown the values below, no need to repeat them here.

2021-04-13 11:50 UTC, HarshCasper commented on docs/sorting-algorithms/quick-sort.mdx
> +
Remove this extra line

2021-04-13 11:50 UTC, HarshCasper commented on docs/sorting-algorithms/quick-sort.mdx
> +
Remove this extra line

2021-04-13 11:50 UTC, HarshCasper commented on docs/sorting-algorithms/quick-sort.mdx
> +on n elements. So time complexity becomes: O(nlogn). And in average case also time complexity:O(nlogn).
Wrap all of this in one line. Also if you have already shown the values below, no need to repeat them here.

2021-04-13 11:50 UTC, HarshCasper commented on docs/sorting-algorithms/quick-sort.mdx
> +<img src="https://i.imgur.com/BEbTHiO.png" width="500" height="350"/>
Did you made this image?

2021-04-13 11:50 UTC, HarshCasper commented on docs/sorting-algorithms/quick-sort.mdx
> +  Sorted!!
Can you follow a slightly more standard example? Take a look at the existing examples and see if you can format yours according to them.

2021-04-13 11:50 UTC, HarshCasper commented on docs/sorting-algorithms/quick-sort.mdx
> +Sorted!!
Can you follow a slightly more standard example? Take a look at the existing examples and see if you can format yours according to them.

2021-04-13 11:50 UTC, HarshCasper commented on docs/sorting-algorithms/quick-sort.mdx
> +<img src="https://i.imgur.com/eBPyIBt.png" width="500" height="350"/>
Did you made this image?

2021-04-13 11:50 UTC, HarshCasper commented on docs/sorting-algorithms/quick-sort.mdx
> +# Algorithm
Use Heading-2

2021-04-13 11:50 UTC, HarshCasper commented on docs/sorting-algorithms/quick-sort.mdx
> +# Code
Use Heading-2

2021-04-13 11:50 UTC, HarshCasper commented on docs/sorting-algorithms/quick-sort.mdx
> +# Sample Input and Output
Use Heading-2

2021-04-13 12:06 UTC, shivammahajancse commented on docs/sorting-algorithms/quick-sort.mdx
> +<img src="https://i.imgur.com/eBPyIBt.png" width="500" height="350"/>
Yes sir

2021-04-13 18:46 UTC, shivammahajancse commented
Sir changes done @HarshCasper @atarax665 @ankitaggarwal23

2021-04-14 09:03 UTC, shivammahajancse commented
sir @iamrajiv  please review

2021-04-14 09:38 UTC, iamrajiv approved these changes

2021-04-16 03:40 UTC, HarshCasper approved these changes

2021-04-16 03:40 UTC, merged