Added Neon Number doc
TesseractCoding/NeoAlgo-Docs pull request #130
Opened 2021-04-09 16:02 UTC by nagasrihith608

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
yes
(Write your answer here.)

### Description
Added Neon Number doc
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixes #59 
(Write your answer here.)

2021-04-09 16:05 UTC, nagasrihith608 commented
@HarshCasper please review this pr. Thank you!

2021-04-09 17:32 UTC, HarshCasper requested changes
The CI has been broken. Can you please fix it?

2021-04-09 17:41 UTC, nagasrihith608 commented
@HarshCasper I fixed the broken CI please check now

2021-04-10 03:54 UTC, HarshCasper requested changes
Tiny changes. Rest looks good to go off for a peer review.

2021-04-10 03:54 UTC, HarshCasper commented on docs/mathematics/neon-number.mdx
> +            n /= 10; // neglecting the last number which we have counted
Don't use comments beside the line of code. Use them above the line of code

2021-04-10 03:54 UTC, HarshCasper commented on docs/mathematics/neon-number.mdx
> +Neon_number(number)
Enclose in a `if __name__ == '__main__'` block

2021-04-10 04:57 UTC, nagasrihith608 commented
> Tiny changes. Rest looks good to go off for a peer review.

@HarshCasper just made those changes please have a look :)

2021-04-10 07:50 UTC, ankitaggarwal23 approved these changes

2021-04-10 07:55 UTC, HarshCasper commented
Hi @nagasrihith608 

Kindly fix the merge conflict. I will merge it soon after.

2021-04-10 08:07 UTC, nagasrihith608 commented
@HarshCasper solved the branch conflict

2021-04-10 09:04 UTC, HarshCasper approved these changes

2021-04-10 09:05 UTC, merged