Counting sort added
TesseractCoding/NeoAlgo-Docs pull request #134
Opened 2021-04-09 17:37 UTC by shivammahajancse

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#50 )

2021-04-09 17:38 UTC, shivammahajancse commented
Please review @HarshCasper @ankitaggarwal23 @gat786 sir

2021-04-10 05:51 UTC, HarshCasper requested changes
Make the same changes I asked here: https://github.com/TesseractCoding/NeoAlgo-Docs/pull/123

2021-04-10 07:44 UTC, shivammahajancse commented
All requested changes done @HarshCasper sir

2021-04-11 12:27 UTC, HarshCasper requested changes

2021-04-11 12:27 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +Counting Sort is a sorting algorithm that sorts the element of array by counting the number of occurence of each distinct elements.In this we have store the occurence of element in count array and th
Keep a space after full stops

2021-04-11 12:27 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +# Explanation for Counting Sort
Keep only `Explanation`. Use Heading-2

2021-04-11 12:27 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +# Introduction
Use Heading-2

2021-04-11 12:27 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +
Don't keep extra spaces before full stops

2021-04-11 12:27 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +<img src="https://i.imgur.com/2TkzRQz.png" width="500" height="350"/>
Have you created this image?

2021-04-11 12:27 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +2. [Ananya9878](https://github.com/Ananya9878) for the [Python implementation](https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/sort/Counting_Sort.py)
Keep in bullet points

2021-04-11 12:27 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +where n is size of an array , and k is element range of the array.
Keep in bullet points. Also keep the values and variables (n, k) in backticks

2021-04-11 12:27 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +# Sample Input and Output
Keep Heading-2

2021-04-11 12:27 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +## Sample 1
No need of this

2021-04-11 12:27 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +### Input :
keep heading-4

2021-04-11 12:27 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +### Output :
keep heading-4

2021-04-11 12:32 UTC, shivammahajancse commented on docs/sorting-algorithms/Counting-sort.mdx
> +<img src="https://i.imgur.com/2TkzRQz.png" width="500" height="350"/>
Yes sir this created by me only

2021-04-12 10:45 UTC, shivammahajancse commented
All changes done @HarshCasper sir

2021-04-13 12:01 UTC, HarshCasper requested changes

2021-04-13 12:01 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +## Explanation
Give a line break

2021-04-13 12:01 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +First store the occurence of each elements in count array. Then modify the count array by storing the sum of counts of previous index and this modified array tell us how many elements are smaller tha
Give a space before the brackets

2021-04-13 12:01 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +
Can you follow a slightly more standard example? Take a look at the existing examples and see if you can format yours according to them.

2021-04-13 12:01 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +* Travesre the given array from end(so that stability maintains) and put the elements by checking our modified count array and given(input) array.
Give a space before the brackets

2021-04-13 12:01 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +* And take an final array(output) and store the elements.
Give a space before the brackets

2021-04-13 12:01 UTC, HarshCasper commented on docs/sorting-algorithms/Counting-sort.mdx
> +- **Average Case Complexity:** `O(n+k)`
No need to have bold

2021-04-13 18:46 UTC, shivammahajancse commented
Sir changes done @HarshCasper @atarax665 @ankitaggarwal23

2021-04-14 09:02 UTC, shivammahajancse commented
sir @iamrajiv  please review

2021-04-14 09:38 UTC, iamrajiv requested changes
@shivammahajancse Resolve the merge conflict.

2021-04-14 09:43 UTC, shivammahajancse commented
sir done @iamrajiv

2021-04-14 17:09 UTC, iamrajiv approved these changes

2021-04-20 05:41 UTC, HarshCasper approved these changes

2021-04-20 05:42 UTC, merged