Article added for N-Queens Problem
TesseractCoding/NeoAlgo-Docs pull request #145
Opened 2021-04-10 06:22 UTC by DEEPIKA-SUK

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

Added the article for N-Queens Problem. The basic layout for the article is:
What is the N Queens Problem?
Explanation for N Queen
Algorithmic Steps
Code in C++ and Python
Sample I/O
Time & Space Complexity

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue: Content: N-Queens #20

2021-04-10 06:25 UTC, DEEPIKA-SUK commented
@HarshCasper Kindly review my PR.

2021-04-11 07:24 UTC, HarshCasper requested changes
Kindly remove the plagiarism or else I will not be able to accept the PR.

2021-04-11 07:24 UTC, HarshCasper commented on docs/backtracking/n-queens.mdx
> +Output is the N x N binary matrices showing possible positions for queens such that they cannot attack each other, where 1 represents the correct place for the queen. If no such valid solution exists
Looks too similar to [this](https://www.geeksforgeeks.org/n-queen-problem-backtracking-3/). Kindly don't plagiarize.

2021-04-11 07:24 UTC, HarshCasper commented on docs/backtracking/n-queens.mdx
> +The backtracking approach is used to solve this problem. Queens are placed one by one in different columns, starting from the leftmost column. While placing a queen in a column, we see if that positi
Copied from [here](https://www.geeksforgeeks.org/n-queen-problem-backtracking-3/)

2021-04-11 07:24 UTC, HarshCasper commented on docs/backtracking/n-queens.mdx
> +- Step 4: If we don't get any solution after trying all rows, then return false.
Copied from [here](https://www.geeksforgeeks.org/printing-solutions-n-queen-problem/)

2021-04-11 07:55 UTC, DEEPIKA-SUK commented
@HarshCasper I have not copied, I have read several articles and then written everything in my own words. Still I will do the necessary changes.

2021-04-11 12:31 UTC, HarshCasper commented
> @HarshCasper I have not copied, I have read several articles and then written everything in my own words. Still I will do the necessary changes.

Yeah, please. I understand your point but here some of the parts are too obvious. We don't want to bring any negative impression on the project.

2021-04-12 03:31 UTC, DEEPIKA-SUK commented
@HarshCasper I have made the necessary changes. Kindly review my PR and let me know if any further changes are to be made.

2021-04-12 06:30 UTC, HarshCasper requested changes

2021-04-12 06:30 UTC, HarshCasper commented on docs/backtracking/n-queens.mdx
> +  |-------|-------|-------|-------|
This is not even a part of the output log. Why is it here?

2021-04-12 06:30 UTC, HarshCasper commented on docs/backtracking/n-queens.mdx
> +- Time Complexity : upperbounded by O(N^N)
Keep the values in backticks

2021-04-12 06:30 UTC, HarshCasper commented on docs/backtracking/n-queens.mdx
> +    bool ndiag[2*N-1], rdiag[2*N-1];
Indent the Code properly

2021-04-12 06:30 UTC, HarshCasper commented on docs/backtracking/n-queens.mdx
> +	solve(board, cols, ndiag, rdiag, 0, "", n);
The input and output statements of C++ and Python don't match. Kindly fix them up

2021-04-12 06:30 UTC, HarshCasper commented on docs/backtracking/n-queens.mdx
> +Now the 4th queen cannot be placed in the 4th row as there exists no safe cell such that no two queens can attack each other. So we will return false and backtrack to the previous row and change the
Keep a line break after this

2021-04-12 06:30 UTC, HarshCasper commented on docs/backtracking/n-queens.mdx
> +Therefore, the answer for N=4 is:
Keep `N=4` in backticks

2021-04-12 06:30 UTC, HarshCasper commented on docs/backtracking/n-queens.mdx
> +Let's take an example, N=4, `X` represents chess queen.
Keep `N=4` in backticks

2021-04-12 06:30 UTC, HarshCasper commented on docs/backtracking/n-queens.mdx
> +This problem can be solved using `backtracking`. Each row and column will contain only one queen. We will start from the first cell of the chessboard. We will move row-wise, and for each row, we will
Keep backtracking in bolds

2021-04-12 06:30 UTC, HarshCasper commented on docs/backtracking/n-queens.mdx
> +This problem can be solved using `backtracking`. Each row and column will contain only one queen. We will start from the first cell of the chessboard. We will move row-wise, and for each row, we will
Don't use short forms like i.e. Replace with `that is`

2021-04-12 06:30 UTC, HarshCasper commented on docs/backtracking/n-queens.mdx
> +This problem can be solved using `backtracking`. Each row and column will contain only one queen. We will start from the first cell of the chessboard. We will move row-wise, and for each row, we will
`We will move row-wise, and for each row, we will see if there exists a column where the queen can be placed safely, i.e., no two queens are at an attacking position, we will include that cell in solution and will proceed further, and if we didn't find any such cell, then we will return false and backtrack to previous cell, change the queen's position.`

Break this into smaller lines.

2021-04-12 12:00 UTC, DEEPIKA-SUK commented
@HarshCasper Kindly review now, I have made all the changes.

2021-04-13 12:10 UTC, HarshCasper approved these changes

2021-04-13 12:12 UTC, merged