Documentation for merge sort algorithm
TesseractCoding/NeoAlgo-Docs pull request #147
Opened 2021-04-10 07:49 UTC by ELITA04

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added documentation for Merge Sort

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue #46

2021-04-10 08:02 UTC, ELITA04 commented
Hi @HarshCasper,

Could you please help me understand why the build is failing? 

Also please review my work and let me know if any changes required.

Thank you!

2021-04-10 10:51 UTC, HarshCasper requested changes
Please fix the build and the merge conflicts. I would be only then able to review the article on a live view.

2021-04-10 10:51 UTC, HarshCasper commented on sidebars.js
> +        '/sorting-algorithms/merge-sort'
Your build is failing because of this. Don't keep relative paths. Just keep `sorting-algorithms/merge-sort` here

2021-04-10 11:03 UTC, ELITA04 commented
@HarshCasper,

That was a silly mistake on my part, sorry about it!

I did the changes please review it now.

2021-04-11 10:08 UTC, ELITA04 commented
@HarshCasper,
I solved the conflict issue as well. Please have a look

Thanks

2021-04-11 12:11 UTC, HarshCasper requested changes
Tiny changes required. Sending it off for a peer review.

2021-04-11 12:11 UTC, HarshCasper commented on docs/sorting-algorithms/merge-sort.mdx
> +**Stage 1: Divide**
Use Heading-4

2021-04-11 12:11 UTC, HarshCasper commented on docs/sorting-algorithms/merge-sort.mdx
> +**Stage 2: Compare and Combine**
Use Heading-4

2021-04-11 12:11 UTC, HarshCasper commented on docs/sorting-algorithms/merge-sort.mdx
> +## Alogrithmic Steps
Just keep `Algorithm`

2021-04-11 12:11 UTC, HarshCasper commented on docs/sorting-algorithms/merge-sort.mdx
> +- Merge the left and right array to get a fully sorted array
Put full-stops at the sentence end

2021-04-11 12:11 UTC, HarshCasper commented on docs/sorting-algorithms/merge-sort.mdx
> +**Input**
Keep heading-4

2021-04-11 12:11 UTC, HarshCasper commented on docs/sorting-algorithms/merge-sort.mdx
> +**Output**
Keep heading-4

2021-04-11 12:11 UTC, HarshCasper commented on docs/sorting-algorithms/merge-sort.mdx
> +**Input**
Keep heading-4

2021-04-11 12:11 UTC, HarshCasper commented on docs/sorting-algorithms/merge-sort.mdx
> +**Output**
Keep heading-4

2021-04-11 12:11 UTC, HarshCasper commented on docs/sorting-algorithms/merge-sort.mdx
> +- **Time Complexity:** O (n log n)
Keep the values in backticks

2021-04-11 12:11 UTC, HarshCasper commented on docs/sorting-algorithms/merge-sort.mdx
> +- **Space Complexity:** O (n)
Keep the values in backticks

2021-04-11 12:19 UTC, nidh-ish requested changes

2021-04-11 12:19 UTC, nidh-ish commented on docs/sorting-algorithms/merge-sort.mdx
> +## Explaination
Make it Explanation.

2021-04-11 12:19 UTC, nidh-ish commented on docs/sorting-algorithms/merge-sort.mdx
> +To understand better, lets take an example of an unsorted array
Make it let us.

2021-04-11 12:19 UTC, nidh-ish commented on docs/sorting-algorithms/merge-sort.mdx
> +The merge sort breaks an array down into smaller arrays until the size of the array is reduced to 1. Since a single element is always considered to be sorted, two contiguous elements can be merged. T
Add comma before and after therefore.

2021-04-11 12:19 UTC, nidh-ish commented on docs/sorting-algorithms/merge-sort.mdx
> +In the next iteration, we compare the 2 lists together, and merge them into a list placing all in a sorted order.
Make it - placing them all in sorted order.

2021-04-11 14:08 UTC, ELITA04 commented
Hi @HarshCasper  and @nidh-ish,

I have made the changes requested.

2021-04-11 14:21 UTC, nidh-ish approved these changes
LGTM.

2021-04-11 14:54 UTC, HarshCasper approved these changes

2021-04-11 14:54 UTC, merged