Searching Algorithms
TesseractCoding/NeoAlgo-Docs pull request #152
Opened 2021-04-10 11:12 UTC by TidbitsJS

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added documentation for searching algorithms.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Closes: #12

2021-04-10 11:15 UTC, TidbitsJS commented
Kindly review @HarshCasper :)

2021-04-10 15:28 UTC, nagasrihith608 requested changes

2021-04-10 15:28 UTC, nagasrihith608 commented on docs/searching-algorithms/searching-algorithms.mdx
> +Few Notable examples -
replace  '-'  with :

2021-04-10 15:28 UTC, nagasrihith608 commented on docs/searching-algorithms/searching-algorithms.mdx
> +With the mindl flow as of binary search, jump search adds its jump step to do searching.
change the spelling mindl to mind

2021-04-10 15:28 UTC, nagasrihith608 commented on docs/searching-algorithms/searching-algorithms.mdx
> +and many as such.
you can delete this line

2021-04-10 15:28 UTC, nagasrihith608 commented on docs/searching-algorithms/searching-algorithms.mdx
> +4. Pass that range to the binary search algorithm
you can add backticks to i and numbers.

2021-04-10 15:28 UTC, nagasrihith608 commented on docs/searching-algorithms/searching-algorithms.mdx
> +As you can note, it works on sorted collection of elements only.
Change it to :
As you can note, it works on a sorted collection of elements only.

2021-04-10 15:30 UTC, nagasrihith608 commented
also @TidbitsJS, you can change all the  '-'  to ':' as it is more appropriate. Also please end all the sentences with a full stops.

2021-04-10 17:29 UTC, TidbitsJS commented
Changes has been made @nagasrihith608 & @HarshCasper :)

2021-04-11 07:04 UTC, HarshCasper requested changes
Brilliant work on this :clap: 

I feel you can bring some extraordinary value through your writing in form of blogs. Tiny changes requested after which it will be merged.

2021-04-11 07:04 UTC, HarshCasper commented on docs/searching-algorithms/searching-algorithms.mdx
> +Searching is a method of finding whether an element or a value exists in the given list of elements or values. If the element exists, then it returns its position. In the real world, there are many u
Few changes:
- `If you want to find something....`
- `you got to need this algorithmic process.`

2021-04-11 07:04 UTC, HarshCasper commented on docs/searching-algorithms/searching-algorithms.mdx
> +* Using it to solve other problems including, knapsack, sudoku, etc.
`Knapsack` and `Sudoku`

Don't use informal conversational words like `etc`

2021-04-11 07:04 UTC, HarshCasper commented on docs/searching-algorithms/searching-algorithms.mdx
> +The practical uses of linear search are a very rare cause of the way its search. It's quite costly (w.r.t time) to go for, e.x., it will be really hard for AWS developers to go through the complete d
`with respect to time`

2021-04-11 07:04 UTC, HarshCasper commented on docs/searching-algorithms/searching-algorithms.mdx
> +The practical uses of linear search are a very rare cause of the way its search. It's quite costly (w.r.t time) to go for, e.x., it will be really hard for AWS developers to go through the complete d
`for, example`

2021-04-11 07:04 UTC, HarshCasper commented on docs/searching-algorithms/searching-algorithms.mdx
> +2. Worst Case - The element to be searched, is the endmost element.
Use bullet points

2021-04-11 07:04 UTC, HarshCasper commented on docs/searching-algorithms/searching-algorithms.mdx
> +If the calculated pos ( probe position ) matches the element to be searched, then it returns the position of the element. Else it will check whether the element is larger than the element present at
Keep `pos` in backticks

2021-04-11 07:04 UTC, HarshCasper commented on docs/searching-algorithms/searching-algorithms.mdx
> +If the collection contains, some, 36 elements then the jump search will take a jump of 6 from the starting i.e Jump from index 0 to 6, then check if the given element is smaller than the 6th element
Replace `i.e` to `that is`

2021-04-11 11:36 UTC, TidbitsJS commented
Done with changes @HarshCasper :)

2021-04-11 12:01 UTC, HarshCasper approved these changes

2021-04-11 12:03 UTC, merged