adding matrix addition
TesseractCoding/NeoAlgo-Docs pull request #164
Opened 2021-04-10 17:39 UTC by aaadddiii

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

fixes #34 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #34

2021-04-10 17:44 UTC, aaadddiii commented
@HarshCasper  please review my pr

2021-04-11 17:10 UTC, HarshCasper requested changes

2021-04-11 17:10 UTC, HarshCasper commented on docs/mathematics/matrix-addition.mdx
> +![image](https://i.postimg.cc/Jn8yyrzg/image.png)
Did you make this diagram?

2021-04-11 17:10 UTC, HarshCasper commented on docs/mathematics/matrix-addition.mdx
> +
You don't need to use `<br/>` repeatedly. `mdx` takes care of it

2021-04-11 17:10 UTC, HarshCasper commented on docs/mathematics/matrix-addition.mdx
> +Consider two matrices A and B , the sum of two matrices A and B will be a matrix which has the same number of rows and columns as A and B. The sum of A and B, denoted A + B, It is computed by adding
Keep `A` and `B` in backticks

2021-04-11 17:10 UTC, HarshCasper commented on docs/mathematics/matrix-addition.mdx
> +Consider two matrices A and B , the sum of two matrices A and B will be a matrix which has the same number of rows and columns as A and B. The sum of A and B, denoted A + B, It is computed by adding
Use proper sentences and grammar. Please do a Grammarly lint at least once.

2021-04-11 17:10 UTC, HarshCasper commented on docs/mathematics/matrix-addition.mdx
> +- Result [i,j] =  A [i,j] + B [i,j]<br/>
Keep `i`, `j`, `A`, `B` in backticks

2021-04-11 17:10 UTC, HarshCasper commented on docs/mathematics/matrix-addition.mdx
> +- Space complexity - O(n*m),, where `n` and `m` are the number of rows and columns respectively
Keep the values in backticks

2021-04-11 17:10 UTC, HarshCasper commented on docs/mathematics/matrix-addition.mdx
> +### Output
Use Heading-4

2021-04-11 17:10 UTC, HarshCasper commented on docs/mathematics/matrix-addition.mdx
> +### Input
Use Heading-4

2021-04-11 17:10 UTC, HarshCasper commented on docs/mathematics/matrix-addition.mdx
> +        result[i][j]  = A[i][j] + B[i][j]
Use an example/explanation. Not pseudocode

2021-04-11 17:21 UTC, aaadddiii commented on docs/mathematics/matrix-addition.mdx
> +![image](https://i.postimg.cc/Jn8yyrzg/image.png)
Yes

2021-04-11 17:53 UTC, aaadddiii commented
@HarshCasper  I have made the changes , can you please review my pr

2021-04-13 12:23 UTC, HarshCasper requested changes

2021-04-13 12:23 UTC, HarshCasper commented on docs/mathematics/matrix-addition.mdx
> +- Display `Result`
Use text for algorithm steps. Use formulae to complement them

2021-04-13 12:23 UTC, HarshCasper commented on docs/mathematics/matrix-addition.mdx
> +int main()
Don't put the entire logic in the `main()` function. Use `main()` only for the driver code.

2021-04-15 10:50 UTC, aaadddiii commented
@HarshCasper  I have made the changes please review it

2021-04-19 12:49 UTC, vybhav72954 requested changes

2021-04-19 12:49 UTC, vybhav72954 commented on docs/mathematics/matrix-addition.mdx
> +
The algorithm can be much more plain text-based, please make changes accordingly.

2021-04-19 16:53 UTC, aaadddiii commented
@vybhav72954  I have made the changes, please review it

2021-04-20 05:47 UTC, HarshCasper approved these changes

2021-04-20 05:49 UTC, merged