sum of divisors added
TesseractCoding/NeoAlgo-Docs pull request #176
Opened 2021-04-11 07:06 UTC by tk315

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

article on sum of divisors added

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#84

2021-04-11 09:43 UTC, atarax665 requested changes

2021-04-11 09:43 UTC, atarax665 commented on docs/mathematics/sum-of-divisors.mdx
> +def sum_of_divisors(n):
Add proper comments where needed.

2021-04-11 09:43 UTC, atarax665 commented on docs/mathematics/sum-of-divisors.mdx
> +  - **Best Case**: O (sqrt(n))
```suggestion
  - **Best Case**: `O (sqrt(n))`
```

2021-04-11 09:43 UTC, atarax665 commented on docs/mathematics/sum-of-divisors.mdx
> +  - **Average Case**: O (sqrt(n))
```suggestion
  - **Average Case**: `O(sqrt(n))`
```

2021-04-11 09:43 UTC, atarax665 commented on docs/mathematics/sum-of-divisors.mdx
> +  - **Worst Case**: O (sqrt(n))
```suggestion
  - **Worst Case**: `O(sqrt(n))`
```

2021-04-11 09:43 UTC, atarax665 commented on docs/mathematics/sum-of-divisors.mdx
> +- Space Complexity: O (1)
```suggestion
- Space Complexity: `O(1)`
```

2021-04-11 10:03 UTC, tk315 commented on docs/mathematics/sum-of-divisors.mdx
> +def sum_of_divisors(n):
done

2021-04-11 10:03 UTC, tk315 commented on docs/mathematics/sum-of-divisors.mdx
> +  - **Best Case**: O (sqrt(n))
done

2021-04-11 10:03 UTC, tk315 commented on docs/mathematics/sum-of-divisors.mdx
> +  - **Average Case**: O (sqrt(n))
done

2021-04-11 10:03 UTC, tk315 commented on docs/mathematics/sum-of-divisors.mdx
> +  - **Worst Case**: O (sqrt(n))
done

2021-04-11 10:03 UTC, tk315 commented on docs/mathematics/sum-of-divisors.mdx
> +- Space Complexity: O (1)
done

2021-04-11 13:21 UTC, tk315 commented
Please review @ankitaggarwal23 @HarshCasper @iamrajiv @atarax665

2021-04-11 16:29 UTC, HarshCasper requested changes

2021-04-11 16:29 UTC, HarshCasper commented on docs/mathematics/sum-of-divisors.mdx
> +Sum of divisors refers to the sum of numbers in the range `1 to n` which perfectly divides `n`.
Have a more detailed introduction. Usually follow this pattern while introducing what you are writing about: 
- Introduce the topic
- Why its relevant
- Prompt the reader to go next

2021-04-11 16:29 UTC, HarshCasper commented on docs/mathematics/sum-of-divisors.mdx
> +
Make it more intuitive and readable with normal English text and not jargons. Use the `Algorithm` section to detail about the formula and steps

2021-04-11 16:29 UTC, HarshCasper commented on docs/mathematics/sum-of-divisors.mdx
> +```
Use only two example. Also order them in a list

2021-04-11 16:29 UTC, HarshCasper commented on docs/mathematics/sum-of-divisors.mdx
> +    so better take long long int */
Give a line break after a comment

2021-04-11 16:29 UTC, HarshCasper commented on docs/mathematics/sum-of-divisors.mdx
> +    #Initilizing sum as 0
Typo here

2021-04-11 16:29 UTC, HarshCasper commented on docs/mathematics/sum-of-divisors.mdx
> +### Input :
Use Heading-4

2021-04-11 16:29 UTC, HarshCasper commented on docs/mathematics/sum-of-divisors.mdx
> +### Output :
Use Heading-4

2021-04-12 04:36 UTC, ankitaggarwal23 approved these changes

2021-04-12 05:37 UTC, iamrajiv approved these changes

2021-04-12 09:00 UTC, HarshCasper approved these changes

2021-04-12 09:03 UTC, merged