Added documentation for stack
TesseractCoding/NeoAlgo-Docs pull request #193
Opened 2021-04-12 08:04 UTC by tanvi355

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
### Description

Documentation for stack and its operations

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #39

2021-04-13 10:08 UTC, tanvi355 commented
@HarshCasper can you please review the PR

2021-04-14 04:22 UTC, HarshCasper requested changes

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +A pile of books or deck of cards can be thought of as an example of a stack in the real world.
Wrap all of this in one single line.

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +- ```display()``` : Prints all the stack elements
Just give the names: 
- Push
- Pop
- Peek
- Empty
- Display 

No need to show them as functions

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +![Imgur](https://i.imgur.com/DfbgV57.png)
Did you make this image?

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +![Imgur](https://i.imgur.com/DfbgV57.png)
Give a line break after this

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +```
Give a text-wise instruction. Not Pseudo code

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +```
Give a text-wise instruction. Not Pseudo code

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +```
Give a text-wise instruction. Not Pseudo code

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +```
Give a text-wise instruction. Not Pseudo code

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +```
Give a text-wise instruction. Not Pseudo code

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +    Peek();
Use Dynamic Input

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +s.peek()
Use Dynamic Input

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +    Peek();
Use Dynamic Input

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +    s.peek()
Use Dynamic Input

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +  - Empty : O(1)
Keep all the values in backticks

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> + - Space Complexity : O(n)
Keep all the values in backticks

2021-04-14 04:22 UTC, HarshCasper commented on docs/data-structures/stack-data-structure.mdx
> +    - [Sangeeta Mishra](https://github.com/SangeetaMishra) and [SowmiyaNarayanan G](https://github.com/GSNCodes) for the [Python implementation](https://github.com/TesseractCoding/NeoAlgo/blob/master
Wrap all the bullet points in one line

2021-04-14 10:55 UTC, tanvi355 commented on docs/data-structures/stack-data-structure.mdx
> +![Imgur](https://i.imgur.com/DfbgV57.png)
Yes, I did.

2021-04-18 18:27 UTC, HarshCasper approved these changes

2021-04-18 18:28 UTC, merged