adding matrix multiplication
TesseractCoding/NeoAlgo-Docs pull request #197
Opened 2021-04-12 11:40 UTC by aaadddiii

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

fixes #34 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #34

2021-04-12 11:44 UTC, aaadddiii commented
@HarshCasper  can you please review my pr

2021-04-12 11:52 UTC, iamrajiv approved these changes

2021-04-13 09:08 UTC, HarshCasper requested changes

2021-04-13 09:08 UTC, HarshCasper commented on docs/mathematics/matrix-multiplication.mdx
> +- print `result`
Use text for algorithm steps. Use formulae to complement them

2021-04-13 09:08 UTC, HarshCasper commented on docs/mathematics/matrix-multiplication.mdx
> +For Example
`Let's have an example:`

2021-04-13 09:08 UTC, HarshCasper commented on docs/mathematics/matrix-multiplication.mdx
> +-   [Hari Krishnan U](https://github.com/Harikrishnan6336) for [Source Code in C++](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/math/matrix_multiplication.cpp)
`for the implementation in C++`

2021-04-13 09:08 UTC, HarshCasper commented on docs/mathematics/matrix-multiplication.mdx
> +-   [Adithya Kurien Peter](https://github.com/aaadddiii) for [Source Code in Python](https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/math/Matrix_multiplication.py)
`for the implementation in Python`

2021-04-13 09:08 UTC, HarshCasper commented on docs/mathematics/matrix-multiplication.mdx
> +    print()
Keep all of this in a function and use a driver code to run this

2021-04-15 10:37 UTC, aaadddiii commented
@HarshCasper  I have made the changes please review it

2021-04-20 07:18 UTC, HarshCasper approved these changes

2021-04-20 07:22 UTC, merged