Added Article for Jump Search
TesseractCoding/NeoAlgo-Docs pull request #200
Opened 2021-04-12 13:20 UTC by deeptea22

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

Have added article for Jump Search

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#30

2021-04-12 13:21 UTC, deeptea22 commented
Hey! @HarshCasper. Please have a look and let me know of the changes, if any. Thank you :)

2021-04-13 09:04 UTC, HarshCasper requested changes
Please remove some unnecessary comments as well :+1:

2021-04-13 09:04 UTC, HarshCasper commented on docs/searching-algorithms/jump-search.mdx
> +Jump search, also known as block search is a searching algorithm for sorted lists. It locates an item by jumping ahead a fixed number of elements instead of traversing through each element.
Can you add some more information here?

2021-04-13 09:04 UTC, HarshCasper commented on docs/searching-algorithms/jump-search.mdx
> +[![list-1.png](https://i.postimg.cc/jSXyNH1B/list-1.png)](https://postimg.cc/xXXkVznP)
Did you make this image?

2021-04-13 09:04 UTC, HarshCasper commented on docs/searching-algorithms/jump-search.mdx
> +``` Consider the above-sorted list. Let n denote the size of the list. Here, n = 9. Therefore, √n (block size) is 3. Let 5 be the element to be found.```
No need to keep triple back-tick on an entire sentence

2021-04-13 09:04 UTC, HarshCasper commented on docs/searching-algorithms/jump-search.mdx
> +```Since the block size is 3, jump three elements ahead. That is, from A[0] to A[2]. Since A[2] is not greater than 5, the block jumps ahead.```
No need to keep triple back-tick on an entire sentence

2021-04-13 09:04 UTC, HarshCasper commented on docs/searching-algorithms/jump-search.mdx
> +```The block had jumped from A[2] to A[5]. Since A[5] is greater than 5, we perform a linear search on that block, but traversing backward.```
No need to keep triple back-tick on an entire sentence

2021-04-13 09:04 UTC, HarshCasper commented on docs/searching-algorithms/jump-search.mdx
> +```The search element, 5, is now found successfully.```
No need to keep triple back-tick on an entire sentence

2021-04-13 09:06 UTC, deeptea22 commented on docs/searching-algorithms/jump-search.mdx
> +[![list-1.png](https://i.postimg.cc/jSXyNH1B/list-1.png)](https://postimg.cc/xXXkVznP)
yes, i have made all of the images :)

2021-04-13 09:39 UTC, deeptea22 commented
Hey! @HarshCasper. Done with all the changes. Please have a look again. Thank you :)

2021-04-13 17:55 UTC, HarshCasper approved these changes

2021-04-13 17:57 UTC, merged