Preorder traversal added
TesseractCoding/NeoAlgo-Docs pull request #218
Opened 2021-04-13 12:00 UTC by shivammahajancse

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#178 )

2021-04-13 12:03 UTC, shivammahajancse commented
Please review sir @HarshCasper @atarax665 @ankitaggarwal23 @gat786

2021-04-14 09:44 UTC, shivammahajancse commented
Sir @iamrajiv please review

2021-04-14 17:12 UTC, shivammahajancse commented
Please review @nidh-ish

2021-04-14 17:23 UTC, iamrajiv requested changes
@shivammahajancse Rename the file to `preorder_traversal.mdx`.

2021-04-14 17:23 UTC, iamrajiv commented on docs/data-structures/preordertraversal.mdx
> +In this type of traversal(Preorder traversal). First we have to visit the root then its left part then right part respectively. In this first visit root then its left part that means we have to trave
@shivammahajancse Break a line after `## Explanation`.

2021-04-14 17:23 UTC, iamrajiv commented on docs/data-structures/preordertraversal.mdx
> + First traverse the root: Node(44).
Remove `.` after `Node(44)`.

2021-04-14 17:23 UTC, iamrajiv commented on docs/data-structures/preordertraversal.mdx
> + Now our Preorder traversal: 44 22 11 33 66 55 77 !!
Remove `!!` after `77`.

2021-04-14 17:26 UTC, iamrajiv requested changes

2021-04-14 17:26 UTC, iamrajiv commented on docs/data-structures/preordertraversal.mdx
> +### Example 1
@shivammahajancse Below paragraphs look more grammatically correct please edit to this

```markdown
## Introduction

A binary tree is a type of tree which have at most two children or we can say almost degree 2. So to traverse the binary tree according to Depth-first search. We have a traversal algorithm called Preorder traversal.

## Explanation

In this type of traversal(Preorder traversal). First, we have to visit the root then the left part then the right part respectively. In this first visit root then its left part that means we have to traverse the whole left subtree after that whole right subtree. Preorder: (root->left->right).
```

2021-04-14 17:40 UTC, shivammahajancse commented
All changes done sir @iamrajiv

2021-04-14 17:53 UTC, iamrajiv approved these changes

2021-04-14 23:19 UTC, nidh-ish requested changes

2021-04-14 23:19 UTC, nidh-ish commented on docs/data-structures/preorder_traversal.mdx
> +### Example 1
Use heading 4.

2021-04-14 23:19 UTC, nidh-ish commented on docs/data-structures/preorder_traversal.mdx
> +A binary tree is a type of tree which have at most two children or we can say at most degree 2. So to traverse the binary tree according to Depth-first search. We have a traversal algorithm called Pr
Add a full stop at the end.

2021-04-14 23:19 UTC, nidh-ish commented on docs/data-structures/preorder_traversal.mdx
> +# Algorithm
Use heading 2.

2021-04-14 23:19 UTC, nidh-ish commented on docs/data-structures/preorder_traversal.mdx
> +# Code
Use heading 2.

2021-04-14 23:19 UTC, nidh-ish commented on docs/data-structures/preorder_traversal.mdx
> +# Sample Input and Output
Use heading 2.

2021-04-14 23:19 UTC, nidh-ish commented on docs/data-structures/preorder_traversal.mdx
> +# Time & Space Complexity
Make it: Complexity Analysis, and use heading 2

2021-04-14 23:19 UTC, nidh-ish commented on docs/data-structures/preorder_traversal.mdx
> +where h is the height of binary tree and n is the number of elements.
Keep h and n in backticks.

2021-04-14 23:19 UTC, nidh-ish commented on docs/data-structures/preorder_traversal.mdx
> +* Right means traverse the whole right subtree in this (root->left->right) order until we get null.
Make it:

For Preorder traversal, we follow the following algorithm:

First, we have to traverse the Binary tree in this order(root->left->right).

Left means traverse the whole left subtree in this order(root->left->right) until we get the left child as null.

Root means the parent of that particular subtree.

Right means traverse the whole right subtree in this (root->left->right) order until we get null.

2021-04-14 23:19 UTC, nidh-ish commented on docs/data-structures/preorder_traversal.mdx
> +# Code
Make the input/output uniform across both the codes as you did in the in-order traversal.

2021-04-15 04:25 UTC, shivammahajancse commented
All changes done @nidh-ish

2021-04-15 04:44 UTC, nidh-ish approved these changes
LGTM

2021-04-15 09:18 UTC, iamrajiv approved these changes

2021-04-15 09:18 UTC, merged