Postorder traversal added
TesseractCoding/NeoAlgo-Docs pull request #219
Opened 2021-04-13 12:01 UTC by shivammahajancse

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#179 )

2021-04-13 12:03 UTC, shivammahajancse commented
Please review sir @HarshCasper @atarax665 @ankitaggarwal23 @gat786

2021-04-14 09:44 UTC, shivammahajancse commented
Sir @iamrajiv please review

2021-04-14 17:12 UTC, shivammahajancse commented
Please review @nidh-ish

2021-04-15 04:45 UTC, nidh-ish commented
@shivammahajancse Make similar changes here as you were asked to do in the in-order and post-order traversal. Run a Grammarly check also.

2021-04-15 05:05 UTC, shivammahajancse commented
All changes done @nidh-ish

2021-04-15 07:43 UTC, nidh-ish requested changes

2021-04-15 07:43 UTC, nidh-ish commented on docs/data-structures/postordertraversal.mdx
> +Binary Tree is a type of tree which have at most two children or we can say at most degree 2. So to traverse the binary tree according to Depth-first search. We have a traversal algorithm called Post
Make it: A Binary Tree

2021-04-15 07:43 UTC, nidh-ish commented on docs/data-structures/postordertraversal.mdx
> +In this type of traversal(Postorder traversal). first, we have to visit left part then right part then its root respectively. In this first visit left part that means we have to traverse the whole le
Make it:

In this type of traversal(Postorder traversal). first, we have to visit the left part then the right part then its root respectively. In this first visit left part that means we have to traverse the whole left subtree in this order (left->right->root) after that whole right subtree in this order (left->right->root) and then visit the root of that subtree. Postorder: (left->right->root).

2021-04-15 07:43 UTC, nidh-ish commented on docs/data-structures/postordertraversal.mdx
> +* Right means traverse the whole right subtree in this (left->right->root) order until we get null.
Make it: For Postorder traversal, we follow the following algorithm:

First, we have to traverse the Binary tree in this order(left->right->root).

Left means traversing the whole left subtree in this order(left->right->root) until we get the left child as null.

Root means the parent of that particular subtree.

Right means traverse the whole right subtree in this (left->right->root) order until we get null.

2021-04-15 07:43 UTC, nidh-ish commented on docs/data-structures/postordertraversal.mdx
> +Postorder traversal : 11 33 22 55 77 66 44
Make stepwise sample input as it asks in the code.

2021-04-15 09:53 UTC, shivammahajancse commented
Sir done @iamrajiv

2021-04-15 13:23 UTC, iamrajiv approved these changes

2021-04-15 13:24 UTC, iamrajiv requested changes
@shivammahajancse Rename this file to `postorder_traversal.mdx`.

2021-04-15 13:36 UTC, shivammahajancse commented
Sir done @iamrajiv

2021-04-15 13:44 UTC, iamrajiv approved these changes

2021-04-17 16:52 UTC, atarax665 requested changes

2021-04-17 16:52 UTC, atarax665 commented on sidebars.js
> -                "data-structures/preorder_traversal"
Do not delete ```data-structures/preorder_traversal```

2021-04-18 07:47 UTC, shivammahajancse commented
Done sir @atarax665

2021-05-05 09:37 UTC, iamrajiv approved these changes

2021-05-12 17:02 UTC, atarax665 requested changes

2021-05-12 17:02 UTC, atarax665 commented on docs/data-structures/postorder_traversal.mdx
> +* First, we have to traverse the Binary tree in this order(left->right->root).
```suggestion
* First, we have to traverse the Binary tree in the order ```left -> right -> root```.
```

2021-05-12 17:02 UTC, atarax665 commented on docs/data-structures/postorder_traversal.mdx
> +* Left means traversing the whole left subtree in this order(left->right->root) until we get left child as null.
```suggestion
* Left means traversing the whole left subtree in this order ```left -> right -> root``` until we get a left child as null. 
```

2021-05-12 17:02 UTC, atarax665 commented on docs/data-structures/postorder_traversal.mdx
> +* Right means traverse the whole right subtree in this (left->right->root) order until we get null.
```suggestion
* Right means traverse the whole right subtree in this ```left -> right -> root``` order until we get null.
```

2021-05-12 17:06 UTC, shivammahajancse commented
Sir all changes done @atarax665

2021-05-12 17:27 UTC, atarax665 commented on docs/data-structures/postorder_traversal.mdx
> +* Right means traverse the whole right subtree in this <span class="x x-first x-last">```</span>left<span class="x x-first x-last"> -&gt; </span>right<span class="x x-first x-last"> -&gt; </span>root
Remove all these tags.

2021-05-12 17:41 UTC, shivammahajancse commented on docs/data-structures/postorder_traversal.mdx
> +* Right means traverse the whole right subtree in this <span class="x x-first x-last">```</span>left<span class="x x-first x-last"> -&gt; </span>right<span class="x x-first x-last"> -&gt; </span>root
Sir done @atarax665

2021-05-17 04:03 UTC, shivammahajancse commented
@atarax665  sir please review

2021-05-18 09:41 UTC, siddharth25pandey approved these changes
@shivammahajancse LGTM 💯 Able to merge

2021-05-18 09:42 UTC, merged