two pointer documentation
TesseractCoding/NeoAlgo-Docs pull request #226
Opened 2021-04-13 17:53 UTC by RuchiGitHu

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
### Description

I want to explain the usage of two pointer algorithm in the article

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

closes #75

2021-04-13 17:56 UTC, RuchiGitHu commented
Please review @HarshCasper @ankitaggarwal23

2021-04-17 17:01 UTC, RuchiGitHu commented
> Please review @HarshCasper @ankitaggarwal23

can anyone review please... @HarshCasper @ankitaggarwal23

2021-04-23 14:12 UTC, RuchiGitHu commented
> Please review @HarshCasper @ankitaggarwal23

Please review @HarshCasper

2021-04-27 10:56 UTC, HarshCasper requested changes
Fix the CI build as well. Do a `yarn build` on your local machine and push the updates only when they pass.

2021-04-27 10:56 UTC, HarshCasper commented on sidebars.js
> +        },
Why is this needed? We have already segregated algorithms.

2021-04-28 14:50 UTC, RuchiGitHu commented
> Fix the CI build as well. Do a `yarn build` on your local machine and push the updates only when they pass.

Please review @HarshCasper .
One thing I want to say that NeoAlgo is just awesome. Thanks for this chance to contribute here, because of this i have build yarn first time.
Thanks again..
Looking forward to contribute here.

2021-05-06 16:43 UTC, RuchiGitHu commented
> > Fix the CI build as well. Do a `yarn build` on your local machine and push the updates only when they pass.
> 
> Please review @HarshCasper .
> One thing I want to say that NeoAlgo is just awesome. Thanks for this chance to contribute here, because of this i have build yarn first time.
> Thanks again..
> Looking forward to contribute here.

Please review @HarshCasper

2021-05-07 14:16 UTC, RuchiGitHu commented
> > Fix the CI build as well. Do a `yarn build` on your local machine and push the updates only when they pass.
> 
> Please review @HarshCasper .
> One thing I want to say that NeoAlgo is just awesome. Thanks for this chance to contribute here, because of this i have build yarn first time.
> Thanks again..
> Looking forward to contribute here.

Please review @HarshCasper

2021-05-18 16:07 UTC, RuchiGitHu commented
Please review @ankitaggarwal23

2021-05-20 21:35 UTC, iamrajiv approved these changes

2021-05-21 05:53 UTC, ankitaggarwal23 approved these changes

2021-05-21 05:53 UTC, merged