Bipartite check documentation
TesseractCoding/NeoAlgo-Docs pull request #234
Opened 2021-04-14 08:49 UTC by Jahnavi-Majji

## Related Issues or Pull Requests

Fixes #33 and resolves #231 and #214

2021-04-14 08:52 UTC, Jahnavi-Majji commented
@HarshCasper made requested changes to the documentation and created a new PR because the build failed continuously in my local machine.

2021-04-16 02:40 UTC, Jahnavi-Majji commented
Can you please review this @HarshCasper ? So that I can make a PR  for the Egg dropping problem?

2021-04-21 13:32 UTC, Jahnavi-Majji commented
@HarshCasper  @ankitaggarwal23  Can you review this? I opened this a week before.

2021-04-27 11:03 UTC, HarshCasper requested changes

2021-04-27 11:03 UTC, HarshCasper commented on docs/graph-algorithms/bipartite-check.mdx
> +- Space Complexity: O(N)
Wrap the values around backticks

2021-04-27 11:03 UTC, HarshCasper commented on docs/graph-algorithms/bipartite-check.mdx
> +- `N` is the number of vertices and `M` is the number of edges.
No need to keep it as a bullet point

2021-04-27 11:03 UTC, HarshCasper commented on docs/graph-algorithms/bipartite-check.mdx
> +[![Screenshot-82.png](https://i.postimg.cc/W4LJJ80T/Screenshot-82.png)](https://postimg.cc/QFmM2p6y)
Did you make this image?

2021-04-27 11:03 UTC, HarshCasper commented on docs/graph-algorithms/bipartite-check.mdx
> +A graph is bipartite if and only if it is two-colorable. Equivalently, a bipartite graph is a graph that does not contain any **odd-length cycles**.
Both of this can be wrapped in one single line

2021-04-27 11:03 UTC, HarshCasper commented on docs/graph-algorithms/bipartite-check.mdx
> +We can use a series of BFS to determine if the given graph is Bipartite
Put a colon at the end of the sentence

2021-05-10 02:48 UTC, HarshCasper commented
Hi @Jahnavi-Majji 

Are you still working on the same?

2021-05-10 08:41 UTC, Jahnavi-Majji commented
Hey @HarshCasper 
I am currently under home isolation and am recovering from covid. Give me a few days, I'll push the requested changes.

2021-05-30 07:52 UTC, ankitaggarwal23 reviewed
Closing this due to inactivity since last 21 days. Thank you for your valuable time.😊

2021-05-30 07:52 UTC, closed without merging