Coin Change Problem Added
TesseractCoding/NeoAlgo-Docs pull request #237
Opened 2021-04-14 12:35 UTC by DEEPALI-SUK

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Added the article for Coin Change Problem. The basic layout for the article is:
What is the Coin Change Problem?
Explanation for Coin Change Problem
Algorithmic Steps
Example
Code in Java and Python
Sample I/O
Time & Space Complexity

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Article for Coin Change Problem #126

2021-04-14 12:38 UTC, DEEPALI-SUK commented
@HarshCasper Kindly, review my PR

2021-04-27 11:24 UTC, HarshCasper requested changes

2021-04-27 11:24 UTC, HarshCasper commented on docs/dynamic-programming/coin-change-problem.mdx
> +- `amount` is the total required amount.
They don't need to be in a bullet point

2021-04-27 11:24 UTC, HarshCasper commented on docs/dynamic-programming/coin-change-problem.mdx
> +print ('Minimum coins required are {}'.format(min_coins))
Put it in a main driver code

2021-04-27 11:24 UTC, HarshCasper commented on docs/dynamic-programming/coin-change-problem.mdx
> +Given an integer `amount`, which represents the total amount of money, an integer array `coins` representing different coin values, and each denomination has an infinite supply of coins. Find what wi
Can you give more context and information?

2021-04-27 11:24 UTC, HarshCasper commented on docs/dynamic-programming/coin-change-problem.mdx
> +10. The final answer will be `dp[n][amount]`.
Use unordered list, not ordered ones

2021-04-27 11:24 UTC, HarshCasper commented on docs/dynamic-programming/coin-change-problem.mdx
> +`Answer = dp[4][10] = 2`
Better use a diagram here

2021-05-04 19:00 UTC, DEEPALI-SUK commented
@HarshCasper I am closing this PR and creating a new one with suggested changes as I am having problems in pulling. Sorry, for the inconvenience caused.

2021-05-04 19:00 UTC, closed without merging