Added Documentation for Queue
TesseractCoding/NeoAlgo-Docs pull request #238
Opened 2021-04-14 13:31 UTC by Saatvik21

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

`Yes`

### Description

I've added the docs for Queue Data Structure. 

`PS- I used C & C++ Code for queue using arrays as there was no code for Java/Python for queue using arrays.`

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes : #194

2021-04-16 05:16 UTC, Saatvik21 commented
@HarshCasper can you please review this PR, so that I can work on another issue.

2021-04-17 12:04 UTC, HarshCasper requested changes

2021-04-17 12:04 UTC, HarshCasper commented on docs/data-structures/queue.mdx
> +  <img width="540" height="400" src="https://user-images.githubusercontent.com/61618767/114686707-ac525500-9d30-11eb-882f-150835a03a58.gif" />
Did you create this GIF file?

2021-04-17 12:04 UTC, HarshCasper commented on docs/data-structures/queue.mdx
> +A ***queue*** is a logical data structure that works on the discipline ***FIFO(First-In-First-Out)***. It is an **ADT (Abstract Data Type)** where the insertion of elements occurs at one end, called
No need of unnecessary bolds. Remove them out from: 
- queue
- ADT 
- rear
- front

2021-04-17 12:04 UTC, HarshCasper commented on docs/data-structures/queue.mdx
> +  defaultValue="cpp"
Keep it C

2021-04-17 12:04 UTC, HarshCasper commented on docs/data-structures/queue.mdx
> +### Enqueue
Use Heading-4

2021-04-17 12:04 UTC, HarshCasper commented on docs/data-structures/queue.mdx
> +### Dequeue
Use Heading-4

2021-04-17 12:04 UTC, HarshCasper commented on docs/data-structures/queue.mdx
> +### Front
Use Heading-4

2021-04-17 12:04 UTC, HarshCasper commented on docs/data-structures/queue.mdx
> +### isEmpty
Use Heading-4

2021-04-17 12:04 UTC, HarshCasper commented on docs/data-structures/queue.mdx
> +### Display
Use Heading-4

2021-04-17 12:04 UTC, HarshCasper commented on docs/data-structures/queue.mdx
> +
Remove the extra line

2021-04-17 13:18 UTC, Saatvik21 commented on docs/data-structures/queue.mdx
> +  <img width="540" height="400" src="https://user-images.githubusercontent.com/61618767/114686707-ac525500-9d30-11eb-882f-150835a03a58.gif" />
Yes I made this GIF animation

2021-04-17 13:42 UTC, Saatvik21 commented
@HarshCasper I've made the required changes. Please Review. Thanks!

2021-04-18 17:46 UTC, HarshCasper approved these changes

2021-04-18 17:48 UTC, merged