double factorial added
TesseractCoding/NeoAlgo-Docs pull request #248
Opened 2021-04-15 02:21 UTC by tk315

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Double Factorial Article added

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#212

2021-04-15 02:24 UTC, tk315 commented
Please review @HarshCasper @ankitaggarwal23 @iamrajiv @atarax665

2021-04-15 13:42 UTC, iamrajiv requested changes

2021-04-15 13:42 UTC, iamrajiv commented on docs/mathematics/double-factorial.mdx
> +## Credits
@tk315 Add credits.

2021-04-15 14:04 UTC, tk315 commented on docs/mathematics/double-factorial.mdx
> +## Credits
Sir this code is written by me

2021-04-16 20:47 UTC, iamrajiv approved these changes

2021-04-18 18:13 UTC, HarshCasper approved these changes

2021-04-18 18:16 UTC, merged