Article for finding the majority element using Moore's voting Algorithm
TesseractCoding/NeoAlgo-Docs pull request #280
Opened 2021-04-15 16:25 UTC by SAY-droid427

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes https://github.com/TesseractCoding/NeoAlgo-Docs/issues/198

2021-04-15 16:28 UTC, SAY-droid427 commented
@iamrajiv @HarshCasper  Please review the PR

2021-04-16 07:08 UTC, iamrajiv approved these changes

2021-04-17 11:34 UTC, HarshCasper requested changes

2021-04-17 11:34 UTC, HarshCasper commented on docs/miscellaneous/moore-voting-algorithm.mdx
> +title: Finding out the majority element using Moore's voting algorithm
It should be just `Moore's voting algorithm`

2021-04-17 11:34 UTC, HarshCasper commented on docs/miscellaneous/moore-voting-algorithm.mdx
> +
Remove the extra line

2021-04-17 11:34 UTC, HarshCasper commented on docs/miscellaneous/moore-voting-algorithm.mdx
> +    { label: 'C++', value: 'cpp', }
Can you add another implementation in Java/Python/Golang ?

2021-04-17 11:34 UTC, HarshCasper commented on docs/miscellaneous/moore-voting-algorithm.mdx
> +
Add an explanation and diagram

2021-04-17 11:34 UTC, HarshCasper commented on docs/miscellaneous/moore-voting-algorithm.mdx
> +`2` occurs twice, so it is the majority element.
Backticks don't work here

2021-04-17 11:34 UTC, HarshCasper commented on docs/miscellaneous/moore-voting-algorithm.mdx
> +`3` occurs only once, hence no majority element exists.
Backticks don't work here

2021-05-10 02:50 UTC, HarshCasper commented
@SAY-droid427 Can you rebase against master and fix the build so that I can give it a final review?

2021-05-11 03:09 UTC, SAY-droid427 commented
> @SAY-droid427 Can you rebase against master and fix the build so that I can give it a final review?

@HarshCasper Could you please tell me how to do that?

2021-05-11 03:10 UTC, SAY-droid427 commented
@HarshCasper The build is fixed but one of the checks is failing. Could you please review now?

2021-05-30 08:02 UTC, ankitaggarwal23 approved these changes

2021-05-30 08:03 UTC, merged