Painting fence || DP ||documentation
TesseractCoding/NeoAlgo-Docs pull request #300
Opened 2021-04-16 09:54 UTC by aaadddiii

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

fixes #154 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #154

2021-04-27 11:49 UTC, HarshCasper requested changes

2021-04-27 11:49 UTC, HarshCasper commented on docs/dynamic-programming/painting-fence.mdx
> +Given a fence with `n` posts and `k` colors , find out the number of ways of painting the fence such that atmost `2` adjacent posts have the same color.
Would appreciate a bit more explanation here

2021-04-27 11:49 UTC, HarshCasper commented on docs/dynamic-programming/painting-fence.mdx
> +Suppose we have a single post, The number of ways of painting the fence with `k` colors is `k` Now we consider `2` posts, Then the number of ways of painting the second fence with the same color as t
Better break this down into consumable bits. Also don't use back-tick formatting indiscriminately

2021-04-27 11:49 UTC, HarshCasper commented on docs/dynamic-programming/painting-fence.mdx
> +- return `total[n-2]`
Don't use formulas here. Better use Text

2021-04-27 11:49 UTC, HarshCasper commented on docs/dynamic-programming/painting-fence.mdx
> +- Space complexity - O(`n`), where `n` is the number of posts
Use backticks around the entire value

2021-05-12 12:42 UTC, aaadddiii commented
@HarshCasper  Can you please review and merge my pr, I have made the changes

2021-05-26 23:03 UTC, iamrajiv approved these changes

2021-05-26 23:03 UTC, merged