count no. of bits in a number added
TesseractCoding/NeoAlgo-Docs pull request #318
Opened 2021-04-17 06:51 UTC by shivammahajancse

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#255 )

2021-04-17 06:53 UTC, shivammahajancse commented
Please review sir @HarshCasper @iamrajiv @ankitaggarwal23 @atarax665 @gat786

2021-04-19 13:01 UTC, vybhav72954 requested changes

2021-04-19 13:01 UTC, vybhav72954 commented on docs/mathematics/count-bits.mdx
> +int main()
The main function shall only have the driver code

2021-04-19 13:01 UTC, vybhav72954 commented on docs/mathematics/count-bits.mdx
> +where `n` is the number of elements.
Credits?

2021-04-19 13:05 UTC, shivammahajancse commented on docs/mathematics/count-bits.mdx
> +where `n` is the number of elements.
Sir code is written by me .

2021-04-19 18:10 UTC, shivammahajancse commented
All requested changes done sir @vybhav72954

2021-04-21 00:44 UTC, iamrajiv requested changes
@shivammahajancse Resolve the merge conflict.

2021-04-24 04:19 UTC, iamrajiv approved these changes

2021-05-12 17:21 UTC, atarax665 commented on docs/mathematics/count-bits.mdx
> +
@shivammahajancse You haven't resolved this yet.

2021-05-12 17:26 UTC, shivammahajancse commented on docs/mathematics/count-bits.mdx
> +
@atarax665 Sir done

2021-05-12 17:37 UTC, tk315 approved these changes

2021-05-14 14:35 UTC, siddharth25pandey approved these changes
@shivammahajancse LGTM 💯 Able to merge

2021-05-14 14:36 UTC, merged