Product of count of bits of each element in array is added
TesseractCoding/NeoAlgo-Docs pull request #325
Opened 2021-04-17 12:55 UTC by shivammahajancse

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#256 )

2021-04-17 12:56 UTC, shivammahajancse commented
Please review sir @HarshCasper @iamrajiv @ankitaggarwal23 @atarax665 @gat786

2021-04-24 04:13 UTC, iamrajiv requested changes
@shivammahajancse Implement the suggested changes.

2021-04-24 04:13 UTC, iamrajiv commented on docs/mathematics/product-of-count-of-bits-of-each-elements.mdx
> +In this article, we will see how to calculate product of count of bits of each element present in array.
```suggestion
In this article, we will see how to calculate the product of the count of bits of each element present in the array.  
```

2021-04-24 04:13 UTC, iamrajiv commented on docs/mathematics/product-of-count-of-bits-of-each-elements.mdx
> +In this we are given an array. We have to calculate the product of bits of each element present in array for that first we have to calculate the number of bits in each element then simply multiply th
```suggestion
In this, we are given an array. We have to calculate the product of bits of each element present in the array so first, we have to calculate the number of bits in each element then simply multiply them.
```

2021-04-24 05:10 UTC, shivammahajancse commented
All changes done sir @iamrajiv

2021-04-24 19:22 UTC, iamrajiv approved these changes

2021-04-26 12:30 UTC, atarax665 requested changes

2021-04-26 12:30 UTC, atarax665 commented on docs/mathematics/product-of-count-of-bits-of-each-elements.mdx
> +## Explanation
Add a line break after this.

2021-04-26 12:30 UTC, atarax665 commented on docs/mathematics/product-of-count-of-bits-of-each-elements.mdx
> +#### Example 1
```suggestion
#### Example :
```

2021-04-26 12:39 UTC, shivammahajancse commented
Changes done sir @atarax665

2021-05-03 06:27 UTC, atarax665 approved these changes

2021-05-03 07:58 UTC, merged