Sieve of erastothenes || documentation || mathematics
TesseractCoding/NeoAlgo-Docs pull request #326
Opened 2021-04-17 13:24 UTC by aaadddiii

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

fixes #303 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #303

2021-04-20 17:43 UTC, atarax665 requested changes

2021-04-20 17:43 UTC, atarax665 commented on docs/mathematics/sieve-of-eratosthenes.mdx
> +
If would be great if you could add some pictures to explain the workflow of the algorithm.

2021-04-20 17:43 UTC, atarax665 commented on docs/mathematics/sieve-of-eratosthenes.mdx
> +    std::cout << '\n';
```suggestion
    cout << '\n';
```

2021-04-20 17:43 UTC, atarax665 commented on docs/mathematics/sieve-of-eratosthenes.mdx
> +#include <iostream>  //Header file
Remove trivial comments.

2021-04-20 17:43 UTC, atarax665 commented on docs/mathematics/sieve-of-eratosthenes.mdx
> +-   [Adithya kurien peter](https://github.com/aaadddiii) for implementation in python
You haven't linked the python code.

2021-04-20 17:43 UTC, atarax665 commented on docs/mathematics/sieve-of-eratosthenes.mdx
> +-   [Rajiv Singh](https://github.com/iamrajiv) for [implementation in c++](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/math/Sieve_of_Eratosthenes.cpp)
```suggestion
-   [Rajiv Singh](https://github.com/iamrajiv) for [implementation in C++](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/math/Sieve_of_Eratosthenes.cpp)
```

2021-04-22 17:14 UTC, aaadddiii commented
@atarax665  I have made the changes can you please review it

2021-04-23 18:14 UTC, atarax665 approved these changes

2021-05-12 12:19 UTC, aaadddiii commented
@HarshCasper  Can you please review and merge my pr

2021-05-26 09:18 UTC, aaadddiii commented
@iamrajiv  can you please review my pr

2021-05-26 23:02 UTC, iamrajiv approved these changes

2021-05-26 23:02 UTC, merged