Perfect number Docs
TesseractCoding/NeoAlgo-Docs pull request #335
Opened 2021-04-17 17:22 UTC by Harikrishnan6336

<!--
Thank you for sending the PR! We appreciate you spending the time to work on these changes.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

Perfect number Docs

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #122

2021-04-19 05:20 UTC, HarshCasper requested changes

2021-04-19 05:20 UTC, HarshCasper commented on docs/mathematics/perfect-number.mdx
> +Consider a number 6. The divisors of 6(excluding itself) is 1, 2, 3. Thier sum 1 + 2 + 3 = 6, So 6 is a perfect number.
Use backticks around numbers and values

2021-04-19 05:20 UTC, HarshCasper commented on docs/mathematics/perfect-number.mdx
> +-   Else Return False
Don't use formulas for algorithm. Instead use plain text.

2021-04-19 12:45 UTC, vybhav72954 approved these changes

2021-04-20 06:02 UTC, HarshCasper approved these changes

2021-04-20 06:05 UTC, merged