Size of binary tree added
TesseractCoding/NeoAlgo-Docs pull request #350
Opened 2021-04-18 07:56 UTC by shivammahajancse

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#330 )

2021-04-18 10:44 UTC, shivammahajancse commented
Please review sir @HarshCasper @iamrajiv @ankitaggarwal23 @atarax665 @gat786

2021-04-18 23:33 UTC, iamrajiv requested changes

2021-04-18 23:33 UTC, iamrajiv commented on docs/data-structures/size-of-binary-tree.mdx
> +
Remove this line break.

2021-04-18 23:33 UTC, iamrajiv requested changes
@shivammahajancse Resolve the merge conflict.

2021-04-23 18:29 UTC, atarax665 commented
Resolve conflict @shivammahajancse

2021-04-23 18:29 UTC, atarax665 approved these changes

2021-04-24 04:01 UTC, iamrajiv approved these changes

2021-04-24 04:02 UTC, iamrajiv requested changes
@shivammahajancse Resolve the merge conflict so that I can merge the PR.

2021-04-24 05:11 UTC, shivammahajancse commented
Done sir @iamrajiv

2021-05-03 17:41 UTC, merged