Hexagonal Number
TesseractCoding/NeoAlgo-Docs pull request #394
Opened 2021-04-19 07:33 UTC by tk315

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Article on Hexagonal Number

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#354

2021-04-19 08:53 UTC, tk315 commented
Please review sir @HarshCasper @iamrajiv @ankitaggarwal23 @atarax665 @gat786 @nidh-ish

2021-04-21 03:47 UTC, tk315 commented
Image has been modified for night mode

2021-04-25 13:30 UTC, tk315 commented
@HarshCasper please review

2021-04-26 09:34 UTC, iamrajiv requested changes
@tk315 Implement the suggested changes.

2021-04-26 09:34 UTC, iamrajiv commented on docs/mathematics/hexagonal-number.mdx
> +Every hexagonal number is a triangular number and every odd triangular number is a hexagonal number. For calculating the `nth` hexagonal number just apply the formula given below. First few hexagonal
```suggestion
Every hexagonal number is a triangular number and every odd triangular number is a hexagonal number. For calculating the `nth` hexagonal number just apply the formula given below. The first few hexagonal few hexagonal numbers are `1`, `6`, `15`, `28`, `45`, `66`, `91`, `120`, `153`, `190`.
```

2021-04-26 09:34 UTC, iamrajiv commented on docs/mathematics/hexagonal-number.mdx
> +If n is integer then x is a hexagonal number
```suggestion
If n is an integer then x is a hexagonal number
```

2021-04-27 14:46 UTC, HarshCasper approved these changes

2021-04-27 14:53 UTC, merged