Added comb sort doc
TesseractCoding/NeoAlgo-Docs pull request #401
Opened 2021-04-19 11:50 UTC by nagasrihith608

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
yes
(Write your answer here.)

### Description
Added comb sort doc
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixed #376 
(Write your answer here.)

2021-04-24 18:47 UTC, vybhav72954 requested changes

2021-04-24 18:47 UTC, vybhav72954 commented on docs/sorting-algorithms/comb-sort.mdx
> +    //Method to swap two elements of an Array
Missing whitespace in comments, refactor them properly

2021-05-30 09:19 UTC, nagasrihith608 commented
@HarshCasper could you please look into this once

2021-05-31 06:58 UTC, ankitaggarwal23 reviewed
This is strictly against the guidelines you have not been assigned to any of the issues and you have spammed it by opening 10+ issue in the repo which is strictly unfair with other participants. I'm closing all your issues and PR. As we are at the end of the program. Thank you for your contribution😊

2021-05-31 06:58 UTC, closed without merging