Added bucket sort
TesseractCoding/NeoAlgo-Docs pull request #404
Opened 2021-04-19 12:42 UTC by nagasrihith608

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
yes
(Write your answer here.)

### Description
Added bucket sort
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixed #375 
(Write your answer here.)

2021-04-24 18:41 UTC, vybhav72954 requested changes

2021-04-24 18:41 UTC, vybhav72954 commented on docs/sorting-algorithms/bucket-sort.mdx
> + //For cin and cout
Comment should look like this `// For cin and cout`

2021-04-24 18:41 UTC, vybhav72954 commented on docs/sorting-algorithms/bucket-sort.mdx
> +//to sort the individual bucket
Style the comment

2021-04-24 18:41 UTC, vybhav72954 commented on docs/sorting-algorithms/bucket-sort.mdx
> +  //to rewrite the values in array in sorted order
Style the comment

2021-04-24 18:41 UTC, vybhav72954 commented on docs/sorting-algorithms/bucket-sort.mdx
> +  //loop to print original array
Style the comment

2021-04-24 18:41 UTC, vybhav72954 commented on docs/sorting-algorithms/bucket-sort.mdx
> +        //joining buckets
Style the comment

2021-05-10 03:28 UTC, HarshCasper commented
Can you rebase against the master to fix the build?

2021-05-17 23:28 UTC, vybhav72954 commented
Updates?

2021-05-30 08:10 UTC, ankitaggarwal23 reviewed
Closing this due to inactivity. Thank you for your valuable time.😊

2021-05-30 08:11 UTC, closed without merging