Number of bits to be flipped to inter convert two numbers Documentation
TesseractCoding/NeoAlgo-Docs pull request #409
Opened 2021-04-20 03:22 UTC by Harikrishnan6336

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

Number of bits to be flipped to inter convert two numbers Documentation

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #274

2021-04-28 07:15 UTC, HarshCasper requested changes

2021-04-28 07:15 UTC, HarshCasper commented on docs/bit-manipulation/no-of-bits-to-be-flipped-to-interconvert-two-numbers.mdx
> +title: Number of bits to be flipped to interconvert two numbers
Use a shorter title

2021-04-28 07:15 UTC, HarshCasper commented on docs/bit-manipulation/no-of-bits-to-be-flipped-to-interconvert-two-numbers.mdx
> +slug: /bit-manipulation/no-of-bits-to-be-flipped-to-interconvert-two-numbers
Use a more compact slug

2021-04-28 07:15 UTC, HarshCasper commented on docs/bit-manipulation/no-of-bits-to-be-flipped-to-interconvert-two-numbers.mdx
> +Given two numbers we have to find the number of bits to be flipped to convert one number to another.
Add a bit more context

2021-04-28 07:15 UTC, HarshCasper commented on docs/bit-manipulation/no-of-bits-to-be-flipped-to-interconvert-two-numbers.mdx
> +We can find such bits by taking an **xor** of the given numbers and counting the number of set bits in them.
wrap in a single line

2021-05-03 02:57 UTC, HarshCasper requested changes

2021-05-03 02:57 UTC, HarshCasper commented on docs/bit-manipulation/count-bits-flipped-to-convert-two-numbers.mdx
> +title: Count number of bits to be flipped to convert two numbers
Adopt a shorter title and file name

2021-05-03 02:57 UTC, HarshCasper commented on docs/bit-manipulation/count-bits-flipped-to-convert-two-numbers.mdx
> +Given two numbers we have to find the number of bits to be flipped to convert one number to another. We have to count the number of bits that are present in same places but is different in value in b
Can you add an example here as well?

2021-05-30 08:11 UTC, ankitaggarwal23 reviewed
Closing this due to inactivity. Thank you for your valuable time.😊

2021-05-30 08:11 UTC, closed without merging