Invert Binary Tree || Data Structures
TesseractCoding/NeoAlgo-Docs pull request #417
Opened 2021-04-21 13:09 UTC by aaadddiii

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

fixes #380 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #380

2021-05-04 12:12 UTC, sid-1207 commented
Is this still open?

2021-05-04 20:30 UTC, aaadddiii commented
Yes

2021-05-10 07:21 UTC, HarshCasper requested changes

2021-05-10 07:21 UTC, HarshCasper commented on docs/data-structures/invert-binary-tree.mdx
> +- Time complexity - O(`n`) , Where `n` is the number of nodes
Keep `O(n)` in backticks

2021-05-10 07:21 UTC, HarshCasper commented on docs/data-structures/invert-binary-tree.mdx
> +- Space complexity - O(`n`)
Keep `O(n)` in backticks

2021-05-10 07:21 UTC, HarshCasper commented on docs/data-structures/invert-binary-tree.mdx
> +
Can you remove this line

2021-05-10 07:21 UTC, HarshCasper commented on docs/data-structures/invert-binary-tree.mdx
> +![image](https://i.postimg.cc/prCp40pH/tree-2.png)
Use proper paragraphs right here

2021-05-10 07:21 UTC, HarshCasper commented on docs/data-structures/invert-binary-tree.mdx
> +
Remove the extra line

2021-05-12 12:22 UTC, aaadddiii commented
@HarshCasper  Can you please review and merge my pr

2021-05-26 09:17 UTC, aaadddiii commented
@iamrajiv  can you please review my pr

2021-05-28 06:35 UTC, iamrajiv approved these changes

2021-05-30 08:12 UTC, ankitaggarwal23 approved these changes

2021-05-30 08:12 UTC, merged