Article for Equal Sum Partition
TesseractCoding/NeoAlgo-Docs pull request #437
Opened 2021-04-24 12:05 UTC by DEEPIKA-SUK

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
Added article for Equal Sum Partition 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue:  #146

2021-04-24 12:09 UTC, DEEPIKA-SUK commented
@HarshCasper Kindly review my PR.

2021-04-24 18:33 UTC, vybhav72954 commented
Link the issue properly

2021-04-24 19:09 UTC, DEEPIKA-SUK commented
> Link the issue properly, Use `#Fixes`

Done

2021-04-26 11:56 UTC, HarshCasper requested changes
Why were changes made to `yarn.lock`? Please revert that and fix the merge conflicts.

2021-04-26 11:56 UTC, HarshCasper commented on docs/dynamic-programming/equal-sum-partition.mdx
> +We have to determine if the given array of positive integers can be divided into two subsets which need not be equal such that the sum of elements of both the subsets is equal. Each element must belo
Add a bit more description. Right now, it won't make any sense to a reader who might not have came across such a problem.

2021-04-26 11:56 UTC, HarshCasper commented on docs/dynamic-programming/equal-sum-partition.mdx
> +- If the sum is even, we will see if we are able to find a subset whose sum is equal to half of `sum`.
Having a better explanation with diagrams and more would be preferred.

2021-04-26 11:56 UTC, HarshCasper commented on docs/dynamic-programming/equal-sum-partition.mdx
> +1. Make an array `dp[n+1][sum/2+1]` where row represents array values and column represents sum values from `0` to `sum` (C++ code follows this approach) or `dp[sum/2+1][n+1]` where column represents
Break this pointer into sub-pointers

2021-04-26 12:21 UTC, DEEPIKA-SUK commented
> Why were changes made to `yarn.lock`? Please revert that and fix the merge conflicts.

I just did yarn install and then yarn start. Please could you tell me how to remove these changes in yarn lock as I don't know how this file got changed. And please could you also tell me how to resolve this sidebar.js conflict. 
Thank you.

2021-05-01 14:42 UTC, DEEPIKA-SUK commented
@HarshCasper I have done the changes, kindly review now.

2021-05-03 12:42 UTC, DEEPIKA-SUK commented
I am getting conflicts while pulling the changes so I need to fork the repo again so I am closing this PR and will open the new PR with all the changes done. Sorry for the inconvenience.

2021-05-03 12:42 UTC, closed without merging