Added documentation on Cutting a Rod problem
TesseractCoding/NeoAlgo-Docs pull request #443
Opened 2021-04-25 15:32 UTC by nidh-ish

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added documentation on Cutting a Rod problem.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #434

2021-04-26 07:06 UTC, HarshCasper requested changes

2021-04-26 07:06 UTC, HarshCasper commented on docs/dynamic-programming/cutting-a-rod.mdx
> +Given a rod of length `n` and an array of prices of all pieces of length `1` to `n`, we need to determine the maximum price that can be obtained by cutting up the rod and selling its pieces.
The introduction is not very intuitive. A better explanation would be needed here.

2021-04-26 07:06 UTC, HarshCasper commented on docs/dynamic-programming/cutting-a-rod.mdx
> +```
A diagrammatic representation would be better here

2021-04-26 07:06 UTC, HarshCasper commented on docs/dynamic-programming/cutting-a-rod.mdx
> +```
Don't substitute algorithm steps with pseudocode. There is a reason why we have actual code implementations here. Use Algorithm to strictly describe how your code works step-wise

2021-04-26 17:34 UTC, nidh-ish commented
@HarshCasper I have made the changes. Please have a look.

2021-05-29 18:21 UTC, nidh-ish commented
@siddharth25pandey @iamrajiv @HarshCasper Please review this PR.

2021-05-30 08:16 UTC, ankitaggarwal23 approved these changes

2021-05-30 08:18 UTC, merged