Added Documentation for Diameter of Binary Tree
TesseractCoding/NeoAlgo-Docs pull request #461
Opened 2021-04-29 16:16 UTC by Saatvik21

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

`Yes`

### Description

I've added an article for diameter of binary tree

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes: #442

2021-04-29 16:23 UTC, Saatvik21 commented
@HarshCasper @iamrajiv Please review this PR!

2021-04-30 04:42 UTC, iamrajiv requested changes
@Saatvik21 Implement the suggested changes.

2021-04-30 04:42 UTC, iamrajiv commented on docs/competitive-programming/diameter-of-BT.mdx
> +* Return the maximum value of above steps.
```suggestion
* Check whether the node passed in recursive function is null; if yes, then return `0`.
* Recursively find the height of the left subtree and right sub-tree.
* Recursively find the diameter of the left sub-tree and right sub-tree.
* Check whether the diameter passes through the root node
  * If yes, then no. of nodes in the path will be `lh + rh + 1` where lh and rh are the heights of left sub-tree and right sub-tree respectively.
  * Else, the diameter will be `max(ld,rd)` where ld and rd are the diameters of the left subtree and right sub-tree respectively.
* Return the maximum value of the above steps.
```

2021-05-02 05:43 UTC, iamrajiv approved these changes

2021-05-03 04:27 UTC, HarshCasper approved these changes

2021-05-03 04:27 UTC, HarshCasper commented
Hi @Saatvik21 

Can you rebase and fix the build?

2021-05-03 05:55 UTC, Saatvik21 commented
@HarshCasper Although the build is successful but the merge conflict watcher is failing. Is there any problem? Also, should I rebase for my other PR as well #431

2021-05-08 15:40 UTC, iamrajiv approved these changes

2021-05-10 03:08 UTC, HarshCasper commented
> @HarshCasper Although the build is successful but the merge conflict watcher is failing. Is there any problem?

Nope. You can ignore that.

2021-05-10 03:08 UTC, merged