Documentation for BigMod Algorithm
TesseractCoding/NeoAlgo-Docs pull request #475
Opened 2021-05-12 17:23 UTC by RaiyanMahin

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES
### Description

Documentation for BigMod Algorithm

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #474

2021-05-12 17:38 UTC, RaiyanMahin commented
@iamrajiv @HarshCasper  @vybhav72954 kindly review

2021-05-12 18:00 UTC, iamrajiv requested changes

2021-05-12 18:00 UTC, iamrajiv commented on docs/competitive-programming/bigmod-algorithm.mdx
> +
Remove this line break.

2021-05-12 18:15 UTC, RaiyanMahin commented on docs/competitive-programming/bigmod-algorithm.mdx
> +
done

2021-05-16 17:46 UTC, RaiyanMahin commented
@atarax665 @iamrajiv  kindly review my PR

2021-05-16 20:40 UTC, iamrajiv approved these changes

2021-05-17 15:02 UTC, RaiyanMahin commented
@atarax665 @ankitaggarwal23 @gat786 kindly review my PR

2021-05-17 17:16 UTC, vybhav72954 approved these changes

2021-05-17 17:25 UTC, RaiyanMahin commented
@vybhav72954 if all things are good, please merge this PR

2021-05-18 09:26 UTC, merged

2021-05-18 09:43 UTC, RaiyanMahin commented
@iamrajiv  add labels please