Phone keypad problem
TesseractCoding/NeoAlgo-Docs pull request #487
Opened 2021-05-16 17:54 UTC by gayatri517

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Both codes in C++ and python are written by me

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #486

2021-05-17 08:34 UTC, gayatri517 commented
Please review my PR @iamrajiv @atarax665 @gat786 @nidh-ish
Thank you

2021-05-18 09:49 UTC, gayatri517 commented
Please review my PR @iamrajiv @atarax665 @gat786 @nidh-ish
Thank you

2021-05-20 06:50 UTC, gayatri517 commented
Please review my PR @iamrajiv @ankitaggarwal23 @atarax665 @gat786 @nidh-ish @siddharth25pandey @bhav09
Thank you

2021-05-22 17:24 UTC, gayatri517 commented
@atarax665 Please review PR

2021-05-24 13:54 UTC, siddharth25pandey requested changes
@gayatri517 Do the suggested changes

2021-05-24 13:54 UTC, siddharth25pandey commented on docs/competitive-programming/phone-keypad.mdx
> +
Write this concept of Algorithm before Giving examples

2021-05-24 13:54 UTC, siddharth25pandey commented on docs/competitive-programming/phone-keypad.mdx
> +```cpp
Write C++ not cpp

2021-05-24 14:10 UTC, gayatri517 commented
@siddharth25pandey I have made the changes and resolved the merge conflict. Kindly review it

2021-05-24 14:14 UTC, siddharth25pandey approved these changes
@gayatri517 LGTM 💯 Able to merge

2021-05-24 14:14 UTC, merged