Height of binary search tree added
TesseractCoding/NeoAlgo-Docs pull request #493
Opened 2021-05-17 13:35 UTC by shivammahajancse

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #334

2021-05-17 13:36 UTC, shivammahajancse commented
Please review @ankitaggarwal23 @siddharth25pandey @atarax665 sir

2021-05-24 14:11 UTC, siddharth25pandey requested changes
@shivammahajancse Do the suggested changes

2021-05-24 14:11 UTC, siddharth25pandey commented on docs/data-structures/height_BST.mdx
> +For calculating Height of BST, we follow the following algorithm:
Do write "following **steps**"

2021-05-24 14:11 UTC, siddharth25pandey commented on docs/data-structures/height_BST.mdx
> +#include<iostream>
Use **bits/stdc+**

2021-05-24 14:11 UTC, siddharth25pandey commented on docs/data-structures/height_BST.mdx
> +```cpp
Write C++ instead of Cpp

2021-05-24 14:11 UTC, siddharth25pandey commented on docs/data-structures/height_BST.mdx
> +     int n;
Write good naming convention

2021-05-24 14:11 UTC, siddharth25pandey commented on docs/data-structures/height_BST.mdx
> +        cin>>d;
Write good naming convention

2021-05-24 14:19 UTC, shivammahajancse commented on docs/data-structures/height_BST.mdx
> +For calculating Height of BST, we follow the following algorithm:
done

2021-05-24 14:19 UTC, shivammahajancse commented on docs/data-structures/height_BST.mdx
> +```cpp
done

2021-05-24 14:19 UTC, shivammahajancse commented on docs/data-structures/height_BST.mdx
> +     int n;
done

2021-05-24 14:19 UTC, shivammahajancse commented on docs/data-structures/height_BST.mdx
> +        cin>>d;
done

2021-05-24 14:20 UTC, shivammahajancse commented
@siddharth25pandey merge conflict solved

2021-05-24 14:22 UTC, shivammahajancse commented
@siddharth25pandey conflict solved

2021-05-24 14:26 UTC, siddharth25pandey approved these changes
@shivammahajancse LGTM 💯 Good to go

2021-05-24 14:26 UTC, merged