Added Documentation for Double Ended Queue
TesseractCoding/NeoAlgo-Docs pull request #498
Opened 2021-05-19 12:06 UTC by Saatvik21

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

`Yes`

### Description

I've added documentation for double ended queue.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes: #484

2021-05-19 12:10 UTC, Saatvik21 commented
@iamrajiv @ankitaggarwal23 @atarax665 @siddharth25pandey please review!

2021-05-20 14:59 UTC, iamrajiv requested changes

2021-05-20 14:59 UTC, iamrajiv commented on sidebars.js
> +		        "competitive-programming/bigmod-algorithm",
@Saatvik21 Please align this properly.

2021-05-20 15:54 UTC, Saatvik21 commented on sidebars.js
> +		        "competitive-programming/bigmod-algorithm",
@iamrajiv Done!

2021-05-21 06:12 UTC, ankitaggarwal23 approved these changes

2021-05-21 16:02 UTC, atarax665 approved these changes

2021-05-22 17:26 UTC, merged