Added Documentation for Middle Element of a Linked List
TesseractCoding/NeoAlgo-Docs pull request #520
Opened 2021-05-25 13:59 UTC by Saatvik21

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

`Yes`

### Description

I've added an article to find the middle element of a linked list.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes: #512

2021-05-25 14:02 UTC, Saatvik21 commented
Please review @atarax665 @iamrajiv @bhav09

2021-05-26 23:05 UTC, iamrajiv approved these changes

2021-05-29 13:24 UTC, siddharth25pandey requested changes
@Saatvik21 Do the suggested changes

2021-05-29 13:24 UTC, siddharth25pandey commented on docs/data-structures/middle-element-of-LL.mdx
> +#include <cmath>
Use single header **bits/stc++**

2021-05-29 13:24 UTC, siddharth25pandey commented on docs/data-structures/middle-element-of-LL.mdx
> +
Also include Test cases for even number of Nodes

2021-05-29 14:00 UTC, Saatvik21 commented
@siddharth25pandey Done the required changes!

2021-05-30 08:26 UTC, ankitaggarwal23 approved these changes

2021-05-30 08:27 UTC, merged