Article on median of two arrays
TesseractCoding/NeoAlgo-Docs pull request #539
Opened 2021-05-29 07:01 UTC by Amit366

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Added Article on median of two arrays

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes: #299

2021-05-29 07:02 UTC, Amit366 commented
@iamrajiv please review

2021-05-29 10:50 UTC, Amit366 commented
@iamrajiv please can help me to resolve the test error??

2021-05-29 17:33 UTC, iamrajiv requested changes
@Amit366 I don't think `fractional-knapsack.mdx` belongs to this PR.

2021-05-29 18:52 UTC, Amit366 commented
@iamrajiv I have removed the fractional knapsack file

2021-05-31 13:16 UTC, ankitaggarwal23 requested changes

2021-05-31 13:16 UTC, ankitaggarwal23 commented on docs/dynamic-programming/median-of-two-arrays.mdx
> +    return mid;
Use single-line comments instead multiline

2021-05-31 13:16 UTC, ankitaggarwal23 commented on docs/dynamic-programming/median-of-two-arrays.mdx
> +C | -12 | -10 | -6 | -5 | -3 | 3 | 4 | 6 | 10 | 12 | 15 |
It would be great if you could should this using a diagrammatic representation

2021-05-31 13:52 UTC, Amit366 commented
@ankitaggarwal23 please review

2021-05-31 15:33 UTC, ankitaggarwal23 requested changes
Don't add phone clicked image you can use the snip tool for taking a screenshot on desktop and Don't add screenshot all add once as you are doing step wise

2021-05-31 15:50 UTC, Amit366 commented
@ankitaggarwal23 now is it fine??

2021-05-31 18:24 UTC, ankitaggarwal23 approved these changes

2021-05-31 18:25 UTC, merged