Documentation for Linear search
TesseractCoding/NeoAlgo-Docs pull request #56
Opened 2021-04-08 12:52 UTC by SAY-droid427

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added the documentation for linear search 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Closes https://github.com/TesseractCoding/NeoAlgo-Docs/issues/13

2021-04-08 13:21 UTC, SAY-droid427 commented
@HarshCasper I cannot understand why the checks are failing. Could you please help me in this?

2021-04-08 13:33 UTC, HarshCasper commented on docs/searching-algorithms/linear-search.md
> +1. [Rajiv Singh]() for the [C++ implementation](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/search/Linear_Search.cpp)
Change `[Rajiv Singh]()` to `[Rajiv Singh](https://github.com/iamrajiv)` and the CI will be fixed

2021-04-08 13:34 UTC, HarshCasper commented
> @HarshCasper I cannot understand why the checks are failing. Could you please help me in this?

I'm fixing the CI for you. Don't worry

2021-04-08 13:43 UTC, HarshCasper commented
Hi @SAY-droid427 

The CI is passing now 😄

2021-04-08 13:49 UTC, HarshCasper requested changes
Can you look at these

2021-04-08 13:49 UTC, HarshCasper commented on docs/searching-algorithms/linear-search.mdx
> +    { label: 'JavaScript', value: 'js', },
It should be `{ label: 'C++', value: 'cpp', },`

2021-04-08 13:49 UTC, HarshCasper commented on docs/searching-algorithms/linear-search.mdx
> +    { label: 'Java', value: 'java', },
We don't have Java here. Remove it up

2021-04-08 13:49 UTC, HarshCasper commented on docs/searching-algorithms/linear-search.mdx
> +# Time & Space Complexity
Keep it `Complexity Analysis`

2021-04-08 13:49 UTC, HarshCasper commented on docs/searching-algorithms/linear-search.mdx
> +Time Complexity: O(1)
It should be `Time & Space` complexity not Time and Time complexity. Also use bulletpoints here

2021-04-08 13:49 UTC, HarshCasper commented on docs/searching-algorithms/linear-search.mdx
> +2. [Ricardo Prins](https://github.com/ricardoprins) for the [Python implementation](https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/search/Linear_Search.py)
I don't think they actually wrote it. Both were added here: https://github.com/TesseractCoding/NeoAlgo/pull/56

Kindly give the apt credits for that

2021-04-08 13:49 UTC, HarshCasper commented on docs/searching-algorithms/linear-search.mdx
> +```
Use a smaller example that is easy to consume. Be minimal :)

2021-04-08 13:49 UTC, HarshCasper commented on docs/searching-algorithms/linear-search.mdx
> +
Use bulleted points

2021-04-08 18:29 UTC, SAY-droid427 commented
@HarshCasper  I am sorry I again faced that error saying:
Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
I really have faced this issue a few times

2021-04-09 03:10 UTC, HarshCasper commented
> @HarshCasper I am sorry I again faced that error saying:
> Updates were rejected because the remote contains work that you do
> hint: not have locally. This is usually caused by another repository pushing
> hint: to the same ref. You may want to first integrate the remote changes
> hint: (e.g., 'git pull ...') before pushing again.
> I really have faced this issue a few times
> I have created another PR.

No worries :) 

Your other PR is failing checks as well. Can you debug it?

2021-04-09 03:10 UTC, closed without merging